### ISSUE TITLE
AssertionError: set(masks.flatten()) must be {0, 1}

### ISSUE THREAD

**Issue by nicebro123** [hq-deng/RD4AD#13]
hello

assert set(masks.flatten()) == {0, 1}, "set(masks.flatten()) must be {0, 1}"
AssertionError: set(masks.flatten()) must be {0, 1}

This error occurs when testing. how should we solve it?
But our image is already a binary map, so this problem should not occur.

**Comment by nicebro123** [comment]
Traceback (most recent call last):
  File ".\main.py", line 134, in <module>
    train(i)
  File ".\main.py", line 112, in train
    auroc_px, auroc_sp, aupro_px = evaluation(encoder, bn, decoder, test_dataloader, device)
  File "C:\Users\Administrator\Desktop\RMPFRKD\test.py", line 88, in evaluation
    aupro_list.append(compute_pro(gt.squeeze(0).cpu().numpy().astype(int),
  File "C:\Users\Administrator\Desktop\RMPFRKD\test.py", line 360, in compute_pro
    assert set(masks.flatten()) == {0, 1}, "set(masks.flatten()) must be {0, 1}"
AssertionError: set(masks.flatten()) must be {0, 1}

**Comment by Mengyuan-Zhao** [comment]
Hello, I have the same problem, did you solve it?

**Comment by LijialinHub** [comment]
这个虽然漏检率很低，但是常常把正常样本也检测出异常，有没有好的方法能避免，大佬

**Comment by LijialinHub** [comment]
> > 你好
> > assert set（masks.flatten（）） == {0， 1}， “set（masks.flatten（）） 必须是 {0， 1}” AssertionError： set（masks.flatten（）） 必须是 {0， 1}
> > 测试时会发生此错误。我们应该如何解决呢？但是我们的图像已经是二进制映射，因此不应该出现此问题。
> > 你好，请问解决了吗，我也出现了这个问题

劝退，如果拿来做项目根本无法落地的，看我上边提的问题

**Comment by LijialinHub** [comment]
> > > > 你好
> > > > assert set（masks.flatten（）） == {0， 1}， “set（masks.flatten（）） 必须是 {0， 1}” AssertionError： set（masks.flatten（）） 必须是 {0， 1}
> > > > 测试时会发生此错误。我们应该如何解决呢？但是我们的图像已经是二进制映射，因此不应该出现此问题。
> > > > 你好，请问解决了吗，我也出现了这个问题
> > 
> > 
> > 劝退，如果拿来做项目根本无法落地的，看我上边提的问题
> 
> 请问有好的模型推荐吗

v185 7674 2393  有偿

**Comment by da981** [comment]
> 你好
> 
> assert set（masks.flatten（）） == {0， 1}， “set（masks.flatten（）） 必须是 {0， 1}” AssertionError： set（masks.flatten（）） 必须是 {0， 1}
> 
> 测试时会发生此错误。我们应该如何解决呢？但是我们的图像已经是二进制映射，因此不应该出现此问题。

Did you solve this problem?

**Comment by Aliciawangyu** [comment]
> hello
> 
> assert set(masks.flatten()) == {0, 1}, "set(masks.flatten()) must be {0, 1}" AssertionError: set(masks.flatten()) must be {0, 1}
> 
> This error occurs when testing. how should we solve it? But our image is already a binary map, so this problem should not occur.

You need to check your dataset to see if there are all zeros or all ones in the GT of defect

**Comment by zyrelu** [comment]
请问怎么解决呢

**Comment by bingcaipeiqiucha** [comment]
> hello  你好
> 
> assert set(masks.flatten()) == {0, 1}, "set(masks.flatten()) must be {0, 1}"assert set（masks.flatten（）） == {0， 1}， “set（masks.flatten（）） 必须是 {0， 1}” AssertionError: set(masks.flatten()) must be {0, 1}AssertionError： set（masks.flatten（）） 必须是 {0， 1}
> 
> This error occurs when testing. how should we solve it?测试时会出现此错误。我们应该如何解决？ But our image is already a binary map, so this problem should not occur.但是我们的图像已经是二进制映射了，所以应该不会出现这个问题。

Hello, I have the same problem, did you solve it?
